### ISSUE TITLE
Add backlogging for successful back ups

### ISSUE THREAD

**Issue by Toprak-Efe** [Ozyegin-Planetary-Robotics-Laboratory/Jetson-TX2-Backup#1]
Currently we have no idea if whether or not a backup was completed successfully or how long it took. Add to the script so that it uploads a final log to the Drive called BACKUP.log for each backup, which should contain the following.

Whether or not the back-up was successful.
The date at which the back-up was started.
The date at which the back-up was finished.
How long the back-up took.
How much space was backed up in total.

**Comment by taannaayyy** [comment]
Added the new features to the script.
